name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Run FastAPI check
        run: |
          python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 --reload & sleep 5

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd frontend
          pip install -r requirements.txt
      - name: Run Streamlit check
        run: |
          streamlit run app.py --server.headless true &
          sleep 5
